### ISSUE TITLE
Windows binaries not working starting from pkg 5.13.0

### ISSUE THREAD

**Issue by robertsLando** [yao-pkg/pkg#85]
Find the reason here: https://github.com/yao-pkg/pkg-fetch/pull/37

Any help fixing this on pkg-fetch side is more then welcome

**Comment by faulpeltz** [comment]
I managed to find the cause for this issue.

The order for placeholders (except bakery which occurs only once) is:

Windows binary: 
``<placeholder in source string> <bakery> <placeholder in bytecode(?)>``

Linux binary:
``<placeholder in bytecode(?)> <bakery> <placeholder in source string>``

The producer always replaces the first occurence, and replacing the source string does nothing
Replacing the correct one fixes the generated binary on windows

Hacking together a quick fix works on my Windows test box
https://github.com/faulpeltz/pkg/commit/f4d254c513152d1694051307f611cd8be2fc0f68

However the fix is bit ugly, maybe there is a more elegant solution.
I'm not sure why the order is like that, maybe it depends on the platform linker settings?

**Comment by robertsLando** [comment]
@faulpeltz Thanks so much for looking at this! Could you submit a PR? I sincerly have no idea why this has changed starting from latest nodejs versions, if you find out more let me know. In the meanwhile please open a PR and also add a comment that reference to this issue
